EXPERIMENT:
  ID: BLT

##Data
DATA:
  SHUFFLE: True
  NUM_WORKER: 16
  SPLIT:
    TRAIN:
      - '20220420'
      - '20220601'
    VAL:
      - '20220608'
    TEST:
      - '20220420'
      # - '20220629'

##Training
TRAIN:
  MAX_EPOCH: 80
  LR: 0.00007
  LR_EPOCH: 1
  LR_DECAY: 0.99
  WEIGHT_DECAY: 0.0001
  BATCH_SIZE: 64
  AUGMENTATION: True

##Network
MODEL:
  VOXEL_SIZE: 0.1 # Used for discretization in x,y,z when creating a sparse tensor 

##Unstable points filter 
FILTER:
  THRESHOLD: 0.84